export const API_ROUTES = {
  USER_SIGNUP: '/auth/signup',
  SEND_OTP: '/auth/otp',
  VERIFY_OTP: '/auth/verify',
  AUTH_CHECK: '/auth/me',
  LOGOUT: '/auth/logout',
  FORGET_PASSWORD: '/auth/password/forget',
  REST_PASSWORD: '/auth/password/reset',
  COMPANY_REGISTER: '/auth/company/register',
  GET_USER_PROFILE: '/user',
  UPDATE_USER_PROFILE: '/user',
  UPDATE_USER_PASSWORD: '/user/password',
  UPDATE_USER_SUGGESTION_LEVEL: '/user/suggestion/level',
  USER_LOGIN: '/auth/login',
  COMPANY_LOGIN: '/auth/company/login',
  ADMIN_LOGIN: '/auth/admin/login',
  GET_ALL_USERS: (page: number, sort: string, search: string, limit: string) =>
    `/admin/users?page=${page}&sort=${sort}&search=${search}&limit=${limit}`,
  UPDATE_USERS: (id: string) => `/admin/users/${id}`,
  UPDATE_USERS_STATUS: (id: string) => `/admin/users/${id}/status`,
  GET_ALL_PROBLEMS_USER: (search: string, page: string, difficulty: string, skill: string) =>
    `/user/problems?${search ? `search=${search}&` : ''}${
      page ? `page=${page}&` : ''
    }${difficulty ? `difficulty=${difficulty}&` : ''}${skill ? `skill=${skill}&` : ''}`,
  GET_PROBLEM_USER: (id: string) => `/user/problems/${id}`,
  RUN_PROBLEM_USER: `/user/problems/run`,
  SUBMIT_PROBLEM_USER: `/user/problems/submit`,
  GET_PROBLEM_UPDATES: (problemId: string, language: string) =>
    `/user/problems/${problemId}/updates?language=${language}`,
  GET_COMPANY: '/company',
  UPDATE_COMPANY: '/company',
  CREATE_CONTEST_BY_COMPANY: '/company/contests',
  GET_ALL_CONTEST_CREATED_BY_COMPANY: (search: string, page: string) =>
    `/company/contests?search=${search}&page=${page}`,
  GET_CONTEST: (id: string) => `/company/contests/${id}`,
  UPDATE_CONTEST: '/company/contests',
  DELETE_CONTEST: (id: string) => `/company/contests/${id}`,

  CREATE_DOMAIN: '/admin/domain',
  GET_ALL_DOMAINS: '/admin/domains',
  DELETE_DOMAIN: (id: string) => `/admin/domain/${id}`,
  CREATE_SKILL: '/admin/skill',
  GET_ALL_SKILLS: '/common/skills',
  DELETE_SKILL: (id: string) => `/admin/skill/${id}`,
  CREATE_PROBLEM: '/admin/problems',
  GET_ALL_PROBLEM_ADMIN_LISTING: (search: string, page: string, sortBy: string) =>
    `/admin/problems?search=${search}&page=${page}&sortBy=${sortBy}`,
  ADD_LANGUAGE: '/admin/problems/language',
  GET_LANGUAGE: (id: string) => `/admin/problems/${id}/language`,
  UPDATE_LANGUAGE: '/admin/problems/language',
  ADD_TESTCASE: '/admin/problems/testcase',
  GET_TESTCASES: (id: string) => `/admin/problems/${id}/testcases`,
  TESTCASE_DELETED: (id: string) => `/admin/problems/${id}/testcase`,
  GET_PROBLEM: (id: string) => `/admin/problems/${id}`,
  UPDATE_PROBLEM: '/admin/problems',
  CHANGE_VISIBILITY: '/admin/problems/visibility',
  GET_ALL_CODERS: '/user/coders',
  FOLLOW_CODER: '/user/coders/follow',
  UNFOLLOW_CODER: (id: string) => `/user/coders/unfollow/${id}`,
  GET_CODER: (id: string) => `/user/coders/${id}/coder`,
  GET_ALL_PLANS: '/user/payments/plans',
  CREATE_ORDER: '/user/payments/create/razorpay-order',
  VERIFY_ORDER: '/user/payments/verify',
  MARK_PAYMENT_FAILED: '/user/payments/mark-failed',
  GET_ALL_PLANS_ADMIN: '/admin/payments/plans',
  UPDATE_PLAN_ADMIN: '/admin/payments/plans/edit',
  GET_ALL_PAYMENTS_ADMIN: (page: number, sort: string, search: string, limit: string) =>
    `/admin/payments?page=${page}&sort=${sort}&search=${search}&limit=${limit}`,

  GET_ALL_UPCOMING_AND_ONGOING_CONTESTS: (page: number) =>
    `/user/contests/upcoming-and-ongoing?page=${page}`,
  GET_ALL_PAST_CONTESTS: (page: number) => `/user/contests/past?page=${page}`,
  GET_USER_CONTEST: (id: string) => `/user/contests/${id}`,
  SUBMIT_CONTEST_PROBLEM: `/user/contests/submit/problem`,
  JOIN_CONTEST_USER: `/user/contests/join`,
  FINISH_CONTEST_USER: `/user/contests/finish`,
  GET_CONTEST_LEADERBOARD: (id: string) => `/user/contests/${id}/leaderboard`,
};
